/* Vistas de consulta: nunca llaman al motor para avanzar la trayectoria. */
(function(){
  'use strict';
  const legacyStore=LMPLegacy.create(localStorage,LMPGameStorage.valid);
  let page='partida',returnScreen='startScreen',archive=null,filter='Todos',query='',lastFocus=null,marketFocus=null;
  const nav=$('#careerNav'),view=$('#careerView'),dialog=$('#vehicleDialog');
  const e=escapeText;
  const count=(n,singular,plural)=>`${n} ${n===1?singular:plural}`;
  const icon={partida:'road',garaje:'collection',hitos:'trophy',historia:'document',legado:'key'};
  const names={partida:'Partida',garaje:'Garaje',hitos:'Hitos',historia:'Historia',legado:'Legado'};
  const achievementsButton=$('#openAchievements');
  nav.innerHTML=Object.keys(names).map(k=>`<button type="button" data-page="${k}">${uiIcon(icon[k])}<span>${names[k]}</span></button>`).join('');
  nav.append(achievementsButton);
  const originalScreen=screen;
  screen=function(id){originalScreen(id);if(id!=='reviewScreen'){returnScreen=id;page='partida';archive=null;}syncNav();};
  function syncNav(){nav.querySelectorAll('[data-page]').forEach(b=>{const on=b.dataset.page===page;b.classList.toggle('active',on);b.setAttribute('aria-current',on?'page':'false');});}
  function snapshot(){if(archive)return archive.state;if(!state)return null;const s=JSON.parse(JSON.stringify(state));if(s.car)s.car.estimatedValue=vehicleValue();s.collection.forEach((v,i)=>v.collectionValue=collectionValue(state.collection[i]));return s;}
  function rows(){const s=snapshot();return s?LMPLegacy.units(s,CARS):[];}
  function photo(r){const c=carById(r.id);return `<div class="album-photo">${carImageMarkup(c)}</div>`;}
  function period(r){return `${r.boughtYear??'Fecha sin registrar'} → ${r.soldYear??r.endYear}`;}
  function card(r,actions=false){return `<article class="album-card">${photo(r)}<div class="album-info"><span class="eyebrow">${e(r.brand)} · ${r.modelYear??'Año sin registrar'}</span><h3>${e(r.model)}</h3><span class="status ${r.owned?'kept':''}">${r.status}</span><p>${period(r)}</p><strong>${r.owned?money(r.value):r.soldFor!=null?money(r.soldFor):'Valor sin registrar'}</strong><small>${r.owned?'Valor estimado del vehículo':'Precio de venta registrado'}</small><button class="ghost" data-unit="${e(r.uid)}">Ver su historia</button>${actions&&r.owned&&r.status!=='En uso'&&!archive&&state?.phase!=='finished'?`<div class="album-actions"><button data-album-use="${e(r.uid)}" ${vehicleActionsLocked()?'disabled':''}>Usar</button><button class="ghost" data-album-sell="${e(r.uid)}" ${vehicleActionsLocked()?'disabled':''}>Vender</button></div>`:''}</div></article>`;}
  function heading(title,copy){return `<div class="view-heading"><span class="eyebrow">Tu vida sobre ruedas${archive?' · recuerdo archivado':''}</span><h1>${title}</h1><p>${copy}</p></div>`;}
  function empty(text){return `<div class="empty-view">${text}</div>`;}
  function bind(root){
    root.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>detail(b.dataset.unit));
    root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));
    root.querySelectorAll('[data-album-use]').forEach(b=>b.onclick=()=>{if(!b.disabled)useCollectionCar(b.dataset.albumUse);});
    root.querySelectorAll('[data-album-sell]').forEach(b=>b.onclick=()=>{if(b.disabled)return;const item=collectionItem(b.dataset.albumSell);if(item&&confirm(`¿Vender ${item.brand} ${item.model} por ${money(collectionSaleValue(item))}?`))sellCollectionCar(item.uid);});
  }
  function detail(uid){const r=rows().find(v=>v.uid===uid);if(!r)return;lastFocus=document.activeElement;const s=snapshot();const moments=LMPLegacy.timeline(s,CARS,EVENTS).filter(m=>m.uid===uid);
    $('#vehicleDetail').innerHTML=`${photo(r)}<span class="eyebrow">${e(r.brand)} · ${r.modelYear??'Año sin registrar'}</span><h2 id="vehicleTitle">${e(r.model)}</h2><p>${r.status} · ${period(r)}</p><div class="detail-grid"><div>Adquisición<strong>${r.boughtFor!=null?money(r.boughtFor):'Sin registrar'}</strong></div><div>${r.owned?'Valor estimado':'Venta'}<strong>${r.owned?money(r.value):r.soldFor!=null?money(r.soldFor):'Sin registrar'}</strong></div><div>Estado<strong>${r.condition!=null?Math.round(r.condition)+'/100':'Sin registro actual'}</strong></div><div>Originalidad<strong>${r.originality!=null?Math.round(r.originality)+'/100':'Sin registro actual'}</strong></div></div><h3>Momentos de esta unidad</h3>${moments.map(m=>`<div class="detail-moment"><b>${m.year} · ${e(m.title)}</b><p>${e(m.text)}</p></div>`).join('')||'<p>El guardado anterior no vinculaba decisiones con esta unidad.</p>'}`;
    dialog.showModal();$('#closeVehicle').focus?.();
  }
  function garage(){const all=rows();const filtered=all.filter(r=>(filter==='Todos'||filter==='Conservados'&&r.owned||filter==='Vendidos'&&r.status==='Vendido')&&`${r.brand} ${r.model} ${r.modelYear??''}`.toLowerCase().includes(query.toLowerCase()));
    view.innerHTML=heading('El garaje de tu vida',`${count(all.filter(r=>r.owned).length,'vehículo conservado','vehículos conservados')} · ${count(all.length,'ficha de adquisición','fichas de adquisición')}. Cada unidad guarda su propia historia.`)+`<div class="view-tools"><label>Buscar vehículo<input id="albumSearch" placeholder="Marca, modelo o año" value="${e(query)}"></label><div class="filter-tabs">${['Todos','Conservados','Vendidos'].map(f=>`<button class="ghost ${filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div></div><div class="album-grid">${filtered.map(r=>card(r,true)).join('')}</div>${!filtered.length?empty('No hay vehículos para este filtro.') :''}`;
    $('#albumSearch').oninput=ev=>{query=ev.target.value;const pos=ev.target.selectionStart;garage();$('#albumSearch').focus?.();$('#albumSearch').setSelectionRange?.(pos,pos);};
    view.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;garage();});bind(view);
  }
  function selectedGoals(){try{const ids=JSON.parse(localStorage.getItem('lmp_car_life_goals_v1')||'[]');const pending=achievementTracker.records().filter(d=>!d.record).map(d=>d.id);return Array.isArray(ids)?[...new Set(ids)].filter(id=>pending.includes(id)).slice(0,3):[];}catch{return [];}}
  function goalCard(d,select=true){const selected=selectedGoals().includes(d.id);return `<article class="goal-card ${d.record?'unlocked':''}"><span class="eyebrow">${e(d.category)}</span><h3>${e(d.name)}</h3><p>${e(d.description)}</p><progress max="${d.target}" value="${d.record?d.target:d.progress}" aria-label="${e(d.name)}"></progress><small>${d.record?'✓ Desbloqueado':`Mejor marca: ${d.metric==='cash'?money(d.progress):d.progress} / ${d.metric==='cash'?money(d.target):d.target}${d.finalOnly?' · al finalizar':''}`}</small>${select&&!d.record?`<button class="ghost ${selected?'active':''}" data-goal="${d.id}" aria-pressed="${selected}">${selected?'✓ Meta elegida':'Elegir como meta'}</button>`:''}</article>`;}
  function bindGoals(root){root.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{let ids=selectedGoals();if(ids.includes(b.dataset.goal))ids=ids.filter(id=>id!==b.dataset.goal);else{if(ids.length>=3){showSaveWarning('Podés elegir hasta 3 metas. Quitá una antes de agregar otra.');return;}ids.push(b.dataset.goal);}try{localStorage.setItem('lmp_car_life_goals_v1',JSON.stringify(ids));}catch{showSaveWarning('No se pudieron guardar las metas elegidas.');return;}if(page==='hitos')hitos();else if(page==='legado')legacy();else renderFinal();});}
  function hitos(){const records=achievementTracker.records();const filtered=records.filter(d=>filter==='Todos'||filter==='Desbloqueados'&&d.record||filter==='Pendientes'&&!d.record||filter==='Mis metas'&&selectedGoals().includes(d.id));view.innerHTML=heading('Pequeñas metas. Grandes historias.',`${achievementTracker.count()} de ${records.length} logros desbloqueados. Permanecen entre trayectorias; las metas de dinero cuentan sólo efectivo disponible.`)+`<div class="filter-tabs">${['Todos','Desbloqueados','Pendientes','Mis metas'].map(f=>`<button class="ghost ${filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><p class="muted">Elegí hasta 3 metas para tu próxima trayectoria. El progreso muestra la mejor marca registrada, no suma distintas partidas.</p><div class="goal-grid">${filtered.map(d=>goalCard(d)).join('')}</div>${!filtered.length?empty('Todavía no hay logros en este filtro.') :''}`;view.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;hitos();});bindGoals(view);}
  function timelineMarkup(s){const rs=LMPLegacy.units(s,CARS);const list=LMPLegacy.timeline(s,CARS,EVENTS).filter(m=>filter==='Todos'||m.type===filter);return `<div class="moments">${list.map(m=>{const r=rs.find(v=>v.uid===m.uid);return `<article class="moment"><div class="moment-year">${m.year}</div>${r?`<button class="moment-photo" data-unit="${e(r.uid)}" aria-label="Ver ${e(r.brand+' '+r.model)}">${carImageMarkup(carById(r.id))}</button>`:`<div class="moment-icon">${uiIcon(m.type==='Historia argentina'?'document':'road')}</div>`}<div><span class="eyebrow">${m.type}</span><h3>${e(m.title)}</h3><p>${e(m.text)}</p>${r?`<button class="ghost" data-unit="${e(r.uid)}">${e(r.brand+' '+r.model)} · ${r.modelYear??'año sin registrar'}</button>`:''}</div></article>`;}).join('')}</div>${!list.length?empty('Todavía no hay momentos en este filtro.') :''}`;}
  function history(){const s=snapshot();if(!s){view.innerHTML=heading('Tu historia','Creá una trayectoria para comenzar a escribirla.');return;}view.innerHTML=heading('La ruta que elegiste',`${e(s.player)} · ${s.startYear} → ${s.year}. Un relato armado con tus vehículos, decisiones y resultados registrados.`)+`<div class="chapter-grid">${LMPLegacy.chapters(s,CARS).map(c=>{const r=rows().find(r=>r.uid===c.uid);return `<article class="chapter">${r?photo(r):''}<div><span class="eyebrow">${c.year??'Tu recorrido'}</span><h2>${e(c.title)}</h2><p>${e(c.text)}</p>${r?`<button class="ghost" data-unit="${e(r.uid)}">Ver vehículo</button>`:''}</div></article>`;}).join('')}</div><h2>Todos los momentos</h2><div class="filter-tabs">${['Todos','Vehículos','Decisiones','Tu vehículo','Historia argentina'].map(f=>`<button class="ghost ${filter===f?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div>${timelineMarkup(s)}`;view.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;history();});bind(view);}
  function finalMarkup(s){const rs=LMPLegacy.units(s,CARS),kept=rs.filter(r=>r.owned);const final=rs.find(r=>r.uid===s.finalSnapshot?.uid)||kept[kept.length-1]||rs[rs.length-1];const value=kept.reduce((n,r)=>n+(Number(r.value)||0),0);const traits=[];if(kept.length>=3)traits.push('Coleccionista');if((s.exhibitionWins||0)>0)traits.push('Figura de exhibiciones');if(rs.length<=2&&rs.length)traits.push('Fiel a sus llaves');if(s.money>=50000)traits.push('Ahorrista');if((s.inheritanceCount||0)>0)traits.push('Guardián del legado');if(!traits.length)traits.push('Una historia propia');
    const records=achievementTracker.records(),unlocked=archive?new Set(archive.achievements.filter(id=>LMPAchievements.definitions.some(d=>d.id===id))).size:achievementTracker.count();const pending=records.filter(d=>!d.record);const goalIds=selectedGoals();const suggestions=[...pending.filter(d=>goalIds.includes(d.id)),pending.find(d=>d.metric==='cash'),pending.find(d=>d.metric==='finalGarage'),pending.find(d=>d.id==='ferrari'),...pending].filter(Boolean);const suggested=[...new Map(suggestions.map(d=>[d.id,d])).values()].slice(0,3);
    return `<div class="legacy-hero">${final?photo(final):'<div class="legacy-symbol">'+uiIcon('road')+'</div>'}<div><span class="eyebrow">${s.startYear} → ${s.endYear||s.year} · una vida sobre ruedas</span><h2>Las llaves de ${e(s.player)}</h2><p>La trayectoria se cierra. Sus vehículos y decisiones quedan en este museo.</p><p class="muted">${e(LMPLife.summary(s))}</p><div class="traits">${traits.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div>${final?`<button class="ghost" data-unit="${e(final.uid)}">${e(final.brand+' '+final.model)} · ${final.modelYear??'año sin registrar'}</button>`:''}</div></div><div class="legacy-stats"><div><span>Dinero disponible</span><strong>${money(s.money)}</strong></div><div><span>Patrimonio en vehículos</span><strong>${money(value)}</strong></div><div><span>Unidades adquiridas</span><strong>${rs.length}</strong></div><div><span>Logros ${archive?'al archivar':'permanentes'}</span><strong>${unlocked} / 31</strong></div></div><p class="muted">El patrimonio es un valor estimado. No se suma al efectivo para desbloquear logros de dinero.</p><h2>Tu colección final</h2><div class="album-grid">${kept.map(r=>card(r)).join('')}</div>${!kept.length?empty('No quedaron vehículos conservados. Los autos vendidos siguen en el garaje histórico.') :''}<div class="legacy-links"><button class="ghost" data-go="garaje">Abrir el garaje histórico</button><button class="ghost" data-go="historia">Recorrer mi historia</button><button class="primary" id="exportMemory">Exportar recuerdo</button></div>${!archive?`<h2>Otra vida, otras metas</h2><p class="muted">Los logros desbloqueados permanecen. Elegí hasta tres metas para una nueva trayectoria.</p><div class="goal-grid">${suggested.map(d=>goalCard(d)).join('')}</div>${!suggested.length?'<p>Completaste todos los logros. Podés comenzar otra historia.</p>':''}`:''}`;
  }
  function entry(){if(archive)return archive;if(!state||state.phase!=='finished')throw Error('El recuerdo se exporta al finalizar una trayectoria.');return {id:state.careerId,at:new Date().toISOString(),state:snapshot(),achievements:achievementTracker.records().filter(d=>d.record).map(d=>d.id)};}
  function bindFinal(root){bind(root);bindGoals(root);const b=$('#exportMemory');if(b)b.onclick=()=>{try{downloadSave(legacyStore.exportRaw(entry()),'LMP-recuerdo-'+entry().id+'.json');}catch(err){showSaveWarning(err.message);}};}
  function renderFinal(){if(!state||state.phase!=='finished')return;$('#resultTitle').textContent='Tu legado sobre ruedas';$('#resultCopy').textContent=`${state.player}, el recorrido llegó hasta ${careerEndYear()}. Conservá tu museo y elegí las próximas metas.`;$('#resultCard').innerHTML=finalMarkup(snapshot());$('#playAgain').textContent='Guardar legado y empezar otra trayectoria';bindFinal($('#resultCard'));}
  function legacy(){let entries=[];let warning='';try{entries=legacyStore.read();}catch(err){warning=err.message;}const s=snapshot();view.innerHTML=heading('Historias que quedan',archive?`${e(archive.state.player)} · museo archivado`: 'Guardá el cierre de cada trayectoria antes de empezar otra.')+(warning?`<p role="alert">${e(warning)}</p>`:'')+`<div class="legacy-links"><button class="ghost" id="importMemory">Importar recuerdo</button>${archive?'<button class="ghost" id="backCurrent">Volver a mi partida actual</button>':''}</div><div class="archive-list">${entries.map(a=>`<button class="archive-card" data-archive="${e(a.id)}"><span>${e(a.state.player)}</span><strong>${a.state.startYear} → ${a.state.endYear||a.state.year}</strong><small>${(a.state.history||[]).filter(h=>!h.reactivatedFromCollection).length} vehículos · abrir museo</small></button>`).join('')}</div>${s?.phase==='finished'?finalMarkup(s):empty('El museo de la trayectoria actual se abrirá al finalizar. Podés visitar los recuerdos guardados arriba.')}`;
    view.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{archive=entries.find(a=>a.id===b.dataset.archive);legacy();});$('#importMemory').onclick=()=>$('#importMemoryFile').click();if(archive)$('#backCurrent').onclick=()=>{archive=null;legacy();};if(s?.phase==='finished')bindFinal(view);
  }
  function navigate(next){page=next;filter='Todos';query='';if(next==='partida'){archive=null;originalScreen(returnScreen);syncNav();return;}originalScreen('reviewScreen');syncNav();if(next==='garaje')garage();else if(next==='hitos')hitos();else if(next==='historia')history();else legacy();}
  nav.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));
  $('#closeVehicle').onclick=()=>dialog.close();dialog.addEventListener('close',()=>lastFocus?.focus?.());dialog.addEventListener('click',ev=>{if(ev.target===dialog)dialog.close();});
  $('#importMemoryFile').onchange=async ev=>{try{const f=ev.target.files?.[0];if(!f)return;archive=legacyStore.importRaw(await f.text());navigate('legado');}catch(err){showSaveWarning(err.message);}finally{ev.target.value='';}};
  const originalReset=reset;reset=function(){if(state?.phase==='finished'){try{legacyStore.archive(snapshot(),achievementTracker.records().filter(d=>d.record).map(d=>d.id));}catch(err){showSaveWarning(err.message);return;}}originalReset();};$('#playAgain').onclick=reset;$('#restartFromStarter').onclick=reset;
  const originalHardReset=hardReset;hardReset=function(){if(state?.phase==='finished'){try{legacyStore.archive(snapshot(),achievementTracker.records().filter(d=>d.record).map(d=>d.id));}catch(err){showSaveWarning(err.message);return;}}originalHardReset();};
  const originalFinish=finish;finish=function(){originalFinish();renderFinal();};
  const originalOpen=openMarket,originalClose=closeMarket;
  openMarket=function(force=false){marketFocus=document.activeElement;originalOpen(force);const m=$('#marketModal');m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.setAttribute('aria-labelledby','marketTitle');m.dataset.forced=force?'true':'false';const focus=m.querySelector('button:not([disabled]):not([style*="none"])');focus?.focus?.();};
  closeMarket=function(){originalClose();marketFocus?.focus?.();};$('#closeMarket').onclick=closeMarket;
  document.addEventListener('keydown',ev=>{const m=$('#marketModal');if(!m.classList.contains('open'))return;if(ev.key==='Escape'&&m.dataset.forced!=='true'){ev.preventDefault();closeMarket();}if(ev.key==='Tab'){const focus=[...m.querySelectorAll('button:not([disabled]),[href],input:not([disabled]),select:not([disabled])')].filter(el=>el.offsetParent!==null);if(!focus.length)return;const first=focus[0],last=focus[focus.length-1];if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus();}}});
  // Al cargar un cierre guardado, init puede haberlo renderizado antes de este script.
  if(state?.phase==='finished')renderFinal();syncNav();
  window.LMPInterface={navigate,renderFinal,snapshot,legacyStore};
})();
